site_name: Guide to Armstrong Creek
theme: 
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'lime'
  logo: 'images/guide.svg'
  feature:
    tabs: true
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
google_analytics:
  - 'UA-112526778-4'
  - 'auto'
